# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-08-13 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20190813_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['expiration_date']},
        ),
    ]
